name: Go
on:
  push:
    branches:
      - '**'
    tags:
      - 'v*.*.*'
  pull_request:
    branches:
      - 'main'

jobs:

  session:
    name: Core
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: 'stable'
          cache: false

      - name: Test
        run: |
          go test -race ./...

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v4
        with:
          version: latest

  pgxkv:
    name: pgxkv
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./pgxkv
    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_USER: pgxkv
          POSTGRES_PASSWORD: pgxkv
          POSTGRES_DB: pgxkv
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: 'stable'
          cache: false

      - name: Construct PGXKV_TEST_DATABASE_URL
        run: |
          echo "PGXKV_TEST_DATABASE_URL=postgres://pgxkv:pgxkv@localhost:5432/pgxkv?sslmode=disable" >> $GITHUB_ENV

      - name: Test
        run: |
          go test ./...

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v4
        with:
          version: latest
